service: website
runtime: python27
threadsafe: yes

handlers:

# Routing for Javacript to serve directly
- url: /(.+\.js)
  static_files: dist/\1
  upload: dist/.*
  secure: always

# Routing for a prod styles.css to serve directly
- url: /(.+\.css)
  static_files: dist/\1
  upload: dist/.*
  secure: always

# Routing for typedoc, assets and favicon.ico to serve directly
- url: /((?:assets|docs)/.*|favicon\.ico)
  static_files: dist/\1
  upload: dist/.*
  secure: always

# Routing for ads.txt file
- url: /ads.txt
  static_files: dist/ads.txt
  upload: dist/ads.txt
  secure: always

# Use index.html for everything else.
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always


# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json
- ^(.*/)?.patch$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

