name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install
        npm run build -- --prod
      env:
        CI: true
    - name: Test
      run: |
        npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        npm e2e --protractor-config=e2e/protractor-ci.conf.js
      env:
        CI: true
