name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 17, 18, latest]

    steps:
    - uses: actions/checkout@v4
    - name: 'Using Node.js version: ${{ matrix.node-version }}, Build type: ${{ matrix.build-type }}'
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: make build
      env:
        CI: true
    - name: Build with AOT
      run: make build-with-aot
      env:
        CI: true
    - name: Test
      run: make test
      env:
        CI: true

    - name: Store test coverage report as artifact
      uses: actions/upload-artifact@master
      with:
        name: Test Coverage
        path: coverage
